version: "3"

services:
  isdb_cw-db:
    environment:
      POSTGRES_USER: nullnumber1
      POSTGRES_PASSWORD: password
      POSTGRES_DB: anathomical_park
    image: postgres
    volumes:
       - ${PERSISTENCE_VOLUME}
    ports:
      - "5432:5432"
